### ISSUE TITLE
print4j version and bundle size

### ISSUE THREAD

**Issue by thielium** [SheetJS/js-adler32#9]
**Issue**

We're trying to dedupe our dependencies, and `adler-32` appears to depend on `printj: ~1.2.2`. We have another lib that depends on a slightly different version.

If we changed it to `printj: ^1.2.2`, we'd be able to dedupe.

**Question**

What's the motivation for the more conservative version? Is there any flexibility, here?

**Comment by SheetJSDev** [comment]
Pushed 1.3.1
